// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1_znznlgJ-bdEgGm_ur5t19_bRA4heog',
    appId: '1:915300267574:web:31ba1f893fa6da17e2ca97',
    messagingSenderId: '915300267574',
    projectId: 'appsistemasinteligentes',
    authDomain: 'appsistemasinteligentes.firebaseapp.com',
    storageBucket: 'appsistemasinteligentes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQGS-ORhBU5dZP-9_KcCsn7qXXKeXbGjo',
    appId: '1:915300267574:android:cb74dc01c2f6159ce2ca97',
    messagingSenderId: '915300267574',
    projectId: 'appsistemasinteligentes',
    storageBucket: 'appsistemasinteligentes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVo2g-lBCXe4YimwFG2awnXKTyc7JvAp8',
    appId: '1:915300267574:ios:9198d20e237e42e2e2ca97',
    messagingSenderId: '915300267574',
    projectId: 'appsistemasinteligentes',
    storageBucket: 'appsistemasinteligentes.firebasestorage.app',
    iosBundleId: 'com.example.flutterSistemasInteligentes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVo2g-lBCXe4YimwFG2awnXKTyc7JvAp8',
    appId: '1:915300267574:ios:9198d20e237e42e2e2ca97',
    messagingSenderId: '915300267574',
    projectId: 'appsistemasinteligentes',
    storageBucket: 'appsistemasinteligentes.firebasestorage.app',
    iosBundleId: 'com.example.flutterSistemasInteligentes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1_znznlgJ-bdEgGm_ur5t19_bRA4heog',
    appId: '1:915300267574:web:267daaa0e2cb6490e2ca97',
    messagingSenderId: '915300267574',
    projectId: 'appsistemasinteligentes',
    authDomain: 'appsistemasinteligentes.firebaseapp.com',
    storageBucket: 'appsistemasinteligentes.firebasestorage.app',
  );
}
